"""
Data-driven neural surrogate for aerodynamic coefficients.

This module trains a fast scikit-learn MLP regressor on a design-of-experiments
(DOE) dataset generated by the OpenAeroStruct solver.  The surrogate learns the
mapping from airfoil geometry + flight condition to (CL, CD, CM).  Once trained,
`SurrogateCFDSolver.evaluate()` provides the same interface as the other aero
solvers in `piml_mdo.aero`, making it a drop-in replacement inside the MDO
pipeline.

The model and preprocessing scalers are saved to disk so that the surrogate can
be reused across pipeline runs without retraining.
"""

import json
import logging
import warnings
from pathlib import Path
from typing import Optional, Tuple

import numpy as np

from .airfoil_geometry import AirfoilGeometry
from .neuralfoil_wrapper import AeroResult
from .openaerostruct_solver import OpenAeroStructSolver, WingPlanform

logger = logging.getLogger(__name__)

try:
    from sklearn.neural_network import MLPRegressor
    from sklearn.preprocessing import StandardScaler
    import joblib

    HAS_SKLEARN = True
except ImportError:  # pragma: no cover
    HAS_SKLEARN = False
    logger.warning("scikit-learn is required for the CFD surrogate.")


class SurrogateCFDSolver:
    """Neural-network surrogate trained on OpenAeroStruct data.

    Parameters
    ----------
    model_dir : str or Path
        Directory where the trained model, scalers, and DOE dataset are saved.
    wing_planform : WingPlanform, optional
        Planform used by the underlying OpenAeroStruct solver for DOE generation.
    n_geo_features : int, optional
        Number of chordwise stations used to describe the airfoil geometry.
    n_samples : int, optional
        Number of DOE samples generated when training from scratch.
    hidden_layers : tuple of int, optional
        Hidden-layer sizes for the MLP regressor.
    max_iter : int, optional
        Maximum number of training iterations for the MLP.
    retrain : bool, optional
        If True, discard any saved model and retrain.
    """

    def __init__(
        self,
        model_dir: str = "results/surrogate_cfd",
        wing_planform: Optional[WingPlanform] = None,
        n_geo_features: int = 20,
        n_samples: int = 60,
        hidden_layers: Tuple[int, ...] = (128, 64, 32),
        max_iter: int = 2000,
        retrain: bool = False,
    ):
        if not HAS_SKLEARN:
            raise ImportError(
                "SurrogateCFDSolver requires scikit-learn and joblib."
            )

        self.model_dir = Path(model_dir)
        self.model_dir.mkdir(parents=True, exist_ok=True)
        self.wing_planform = wing_planform or WingPlanform()
        self.n_geo_features = n_geo_features
        self.n_samples = n_samples
        self.hidden_layers = hidden_layers
        self.max_iter = max_iter

        self._cache: dict[tuple, AeroResult] = {}
        self._eval_count = 0

        self.model: Optional[MLPRegressor] = None
        self.x_scaler: Optional[StandardScaler] = None
        self.y_scaler: Optional[StandardScaler] = None

        if not retrain:
            self._load()

    @property
    def eval_count(self) -> int:
        return self._eval_count

    @property
    def is_trained(self) -> bool:
        return self.model is not None

    def reset_count(self):
        """Clear the evaluation counter and cache."""
        self._eval_count = 0
        self._cache.clear()

    def evaluate(
        self,
        coordinates: Tuple[np.ndarray, np.ndarray],
        alpha: float,
        Re: float,
        mach: float = 0.0,
    ) -> AeroResult:
        """Predict aerodynamic coefficients using the trained surrogate.

        Args
        ----
        coordinates : (x, y) full airfoil coordinates.
        alpha : angle of attack [deg].
        Re : Reynolds number (dimensionless, based on chord).
        mach : Mach number.

        Returns
        -------
        AeroResult with predicted CL, CD, CM about c/4, and L/D.
        """
        if not self.is_trained:
            raise RuntimeError(
                "SurrogateCFDSolver has not been trained. Call train() first."
            )

        geo_hash = self._geometry_hash(coordinates)
        cache_key = (geo_hash, round(float(alpha), 6), float(Re), float(mach))
        if cache_key in self._cache:
            return self._cache[cache_key]

        x_feat = self._geometry_features(coordinates)
        x_oper = np.array([alpha, np.log10(max(Re, 1e3)), mach])
        x = np.concatenate([x_feat, x_oper]).reshape(1, -1)
        x_scaled = self.x_scaler.transform(x)

        y_scaled = self.model.predict(x_scaled)
        y = self.y_scaler.inverse_transform(y_scaled)[0]
        cl, cd, cm = float(y[0]), float(y[1]), float(y[2])

        self._eval_count += 1
        result = AeroResult(
            cl=cl,
            cd=cd,
            cm=cm,
            ld_ratio=cl / cd if cd > 1e-10 else 0.0,
            alpha=alpha,
            Re=Re,
            mach=mach,
            converged=True,
        )
        self._cache[cache_key] = result
        return result

    def train(
        self,
        baseline_airfoil: str = "2412",
        n_cst_upper: int = 6,
        n_cst_lower: int = 6,
        alpha_bounds: Tuple[float, float] = (-2.0, 10.0),
        re_bounds: Tuple[float, float] = (2e5, 5e6),
        mach_bounds: Tuple[float, float] = (0.0, 0.25),
        weight_noise: float = 0.08,
        random_seed: Optional[int] = 42,
    ):
        """Generate a DOE and train the neural surrogate.

        The baseline NACA airfoil is perturbed in CST weight space to create a
        small family of realistic airfoils.  OpenAeroStruct evaluates each
        geometry at sampled flight conditions.
        """
        rng = np.random.default_rng(random_seed)

        logger.info(
            "Generating %d DOE samples with OpenAeroStruct...", self.n_samples
        )
        hf_solver = OpenAeroStructSolver(
            wing_planform=self.wing_planform,
            num_x=5,
            num_y=9,
            with_viscous=True,
        )

        baseline = AirfoilGeometry.naca4(baseline_airfoil, n_weights=n_cst_upper)
        base_vec = baseline.design_vector
        n_params = len(base_vec)

        # Fixed geometry feature stations
        self._xi_stations = np.linspace(0.0, 1.0, self.n_geo_features)

        X_list, y_list = [], []
        n_generated = 0
        max_attempts = self.n_samples * 3

        while n_generated < self.n_samples and max_attempts > 0:
            max_attempts -= 1

            # Sample a geometry by perturbing the baseline CST weights
            if n_generated == 0:
                sample_vec = base_vec.copy()
            else:
                noise = rng.normal(scale=weight_noise, size=n_params)
                sample_vec = base_vec + noise
                # Keep the airfoil physically reasonable (positive thickness)
                sample_vec = np.clip(sample_vec, 0.01, 0.5)

            geom = AirfoilGeometry.from_design_vector(
                sample_vec, n_upper=n_cst_upper
            )
            coords = geom.full_coordinates(150)

            # Sample operating point
            alpha = float(rng.uniform(*alpha_bounds))
            Re = float(10 ** rng.uniform(np.log10(re_bounds[0]), np.log10(re_bounds[1])))
            mach = float(rng.uniform(*mach_bounds))

            try:
                result = hf_solver.evaluate(coords, alpha, Re, mach)
            except Exception as exc:
                logger.debug("OpenAeroStruct DOE sample failed: %s", exc)
                continue

            if not result.converged:
                continue

            features = self._geometry_features(coords)
            x = np.concatenate(
                [features, np.array([alpha, np.log10(max(Re, 1e3)), mach])]
            )
            X_list.append(x)
            y_list.append([result.cl, result.cd, result.cm])
            n_generated += 1

        if n_generated < 10:
            raise RuntimeError(
                f"Too few successful DOE samples ({n_generated}); cannot train surrogate."
            )

        X = np.vstack(X_list)
        y = np.vstack(y_list)

        logger.info(
            "Training MLP surrogate on %d samples (%d features)...",
            X.shape[0],
            X.shape[1],
        )
        self.x_scaler = StandardScaler()
        self.y_scaler = StandardScaler()
        X_scaled = self.x_scaler.fit_transform(X)
        y_scaled = self.y_scaler.fit_transform(y)

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            self.model = MLPRegressor(
                hidden_layer_sizes=self.hidden_layers,
                activation="relu",
                solver="adam",
                max_iter=self.max_iter,
                early_stopping=True,
                validation_fraction=0.15,
                n_iter_no_change=20,
                random_state=random_seed,
            )
            self.model.fit(X_scaled, y_scaled)

        logger.info(
            "Surrogate training complete (iterations: %d, final loss: %.6f).",
            self.model.n_iter_,
            self.model.loss_,
        )

        self._save_dataset(X, y)
        self._save()

    def _geometry_hash(self, coordinates: Tuple[np.ndarray, np.ndarray]) -> str:
        """Stable hash of airfoil coordinates for caching."""
        import hashlib

        x, y = coordinates
        data = np.ascontiguousarray(np.column_stack([x, y]))
        return hashlib.sha256(data.tobytes()).hexdigest()[:16]

    def _geometry_features(self, coordinates: Tuple[np.ndarray, np.ndarray]) -> np.ndarray:
        """Convert full airfoil coordinates to a fixed-length feature vector.

        The vector contains upper-surface and lower-surface y/c values at a
        fixed set of chordwise stations.  This is invariant to the number of
        points in the input coordinate arrays.
        """
        x_raw, y_raw = coordinates
        x_raw = np.asarray(x_raw).ravel()
        y_raw = np.asarray(y_raw).ravel()

        c = x_raw.max() - x_raw.min()
        if c < 1e-6:
            c = 1.0
        x_norm = (x_raw - x_raw.min()) / c

        # Build upper/lower lookup tables
        xu = np.unique(np.round(x_norm, decimals=8))
        if len(xu) < 3:
            return np.zeros(2 * self.n_geo_features)

        upper = np.full_like(xu, -1e9)
        lower = np.full_like(xu, 1e9)
        for i, xv in enumerate(xu):
            mask = np.abs(x_norm - xv) < 1e-6
            if np.any(mask):
                upper[i] = y_raw[mask].max() / c
                lower[i] = y_raw[mask].min() / c

        if not hasattr(self, "_xi_stations"):
            self._xi_stations = np.linspace(0.0, 1.0, self.n_geo_features)

        y_u = np.interp(self._xi_stations, xu, upper, left=0.0, right=0.0)
        y_l = np.interp(self._xi_stations, xu, lower, left=0.0, right=0.0)
        return np.concatenate([y_u, y_l])

    def _save_dataset(self, X: np.ndarray, y: np.ndarray):
        """Write the DOE dataset to disk for traceability."""
        dataset_path = self.model_dir / "doe_dataset.npz"
        np.savez(dataset_path, X=X, y=y)
        logger.info("Saved DOE dataset to %s", dataset_path)

    def _save(self):
        """Persist model and scalers."""
        joblib.dump(self.model, self.model_dir / "surrogate_model.pkl")
        joblib.dump(self.x_scaler, self.model_dir / "x_scaler.pkl")
        joblib.dump(self.y_scaler, self.model_dir / "y_scaler.pkl")
        metadata = {
            "n_geo_features": self.n_geo_features,
            "hidden_layers": self.hidden_layers,
            "n_samples": self.n_samples,
        }
        with open(self.model_dir / "metadata.json", "w") as f:
            json.dump(metadata, f, indent=2)
        logger.info("Saved surrogate model to %s", self.model_dir)

    def _load(self):
        """Load a previously trained model and scalers if available."""
        model_path = self.model_dir / "surrogate_model.pkl"
        x_scaler_path = self.model_dir / "x_scaler.pkl"
        y_scaler_path = self.model_dir / "y_scaler.pkl"

        if not all(p.exists() for p in (model_path, x_scaler_path, y_scaler_path)):
            logger.info("No pre-trained surrogate found in %s", self.model_dir)
            return

        try:
            self.model = joblib.load(model_path)
            self.x_scaler = joblib.load(x_scaler_path)
            self.y_scaler = joblib.load(y_scaler_path)
            if (self.model_dir / "metadata.json").exists():
                with open(self.model_dir / "metadata.json") as f:
                    metadata = json.load(f)
                self.n_geo_features = metadata.get("n_geo_features", self.n_geo_features)
                self.hidden_layers = tuple(metadata.get("hidden_layers", self.hidden_layers))
            logger.info("Loaded pre-trained surrogate from %s", self.model_dir)
        except Exception as exc:
            logger.warning("Failed to load surrogate model: %s", exc)
            self.model = None
            self.x_scaler = None
            self.y_scaler = None
